apiVersion: apps/v1
kind: Deployment
metadata:
  name: mem-user
  labels:
    app: memuser
spec:
  replicas: 3
  selector:
    matchLabels:
      app: memuser
  template:
    metadata:
      labels:
        app: memuser
    spec:
      containers:
      - name: memuser
        image: ghcr.io/xphyr/k8s_memuser_advanced:latest
        command: ["/app/memuser"]
        args: ["-memory=300", "-hold=true", "-fast=true"]
        resources:
          requests:
            memory: "10Mi"
          limits:
            memory: "100Mi"
